In [1]:
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'

import keras
import numpy as np

Using TensorFlow backend.


#### 에러 레벨 설정
- "C:\Users\USER\venv\computer-vision\Lib\site-packages\tensorflow\__init__.py"에 아래 내용 추가하기
    - logging.set_verbosity(logging.ERROR)
    - os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'

In [2]:
x_train = np.array([[0],[1]])
y_train = x_train * 2 + 1
print('x_train:\n', x_train)
print('y_train:\n', y_train)

x_test = np.array([[2],[3]])
y_test = x_test * 2 + 1
print('x_test:\n', x_test)
print('y_test:\n', y_test)

x_train:
 [[0]
 [1]]
y_train:
 [[1]
 [3]]
x_test:
 [[2]
 [3]]
y_test:
 [[5]
 [7]]


##### keras에서 모델을 만드는 방법
- 순차 모델 : Sequential
- 함수형 모델 : Functional API

In [3]:
from keras.models import Sequential
from keras.layers import Dense

In [4]:
model = Sequential()
model.add(Dense(1, input_shape=(1,)))