입력 -> 중간층 -> 중간층 -> 출력 노드 수가 2->3->2->1 인 네트워크를 만드세요

In [12]:
import keras
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Activation

x_train = np.array([[0,1],[2,3],[4,5]])
# y = x0 + x1
# y_train = x_train[:,0] + x_train[:,1]
# y_train = np.sum(x_train, axis=1)
y_train = np.array([[x.sum()] for x in x_train])   # 2차원 array 형태
print('x_train:\n', x_train)
print('y_train:\n', y_train)

x_test = np.array([[6,7],[8,9]])
# y_test = x_test[:,0] + x_test[:,1]
# y_test = np.sum(x_test, axis=1)
y_test = np.array([[x.sum()] for x in x_test])   # 2차원 array 형태
print('x_test:\n', x_test)
print('y_test:\n', y_test)

model = Sequential()
model.add(Dense(3, input_dim=2))
model.add(Dense(2))
model.add(Dense(1))

model.summary()

model.compile('SGD', 'mse')
history = model.fit(x_train, y_train, batch_size=3, epochs=1000, verbose=0)

y_predict = model.predict(x_test)
print('y_predict'); print(y_predict)
print('y_test'); print(y_test)

x_train:
 [[0 1]
 [2 3]
 [4 5]]
y_train:
 [[1]
 [5]
 [9]]
x_test:
 [[6 7]
 [8 9]]
y_test:
 [[13]
 [17]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_34 (Dense)             (None, 3)                 9         
_________________________________________________________________
dense_35 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_36 (Dense)             (None, 1)                 3         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
y_predict
[[13.000021]
 [17.000027]]
y_test
[[13]
 [17]]
