입력 -> 중간층 -> 출력으로 구성된 노드수가 1 -> 2 -> 1 인 fully connected 네트워크를 만드세요

In [1]:
import keras
import numpy as np

Using TensorFlow backend.


In [2]:
x_train = np.array([[0],[1]])
y_train = x_train * 2 + 1
print('x_train:\n', x_train)
print('y_train:\n', y_train)

x_test = np.array([[2],[3]])
y_test = x_test * 2 + 1
print('x_test:\n', x_test)
print('y_test:\n', y_test)

x_train:
 [[0]
 [1]]
y_train:
 [[1]
 [3]]
x_test:
 [[2]
 [3]]
y_test:
 [[5]
 [7]]


In [3]:
from keras.models import Sequential
from keras.layers import Dense, Activation

In [4]:
model = Sequential()
model.add(Dense(2, input_shape=(1,)))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('sigmoid'))

In [5]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 4         
_________________________________________________________________
activation_1 (Activation)    (None, 2)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 7
Trainable params: 7
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.compile('SGD', 'mse')

In [7]:
history = model.fit(x_train, y_train, batch_size=2, epochs=1000, verbose=0)

In [8]:
y_predict = model.predict(x_test)
print('y_predict'); print(y_predict)
print('y_test'); print(y_test)

y_predict
[[0.945775]
 [0.945775]]
y_test
[[5]
 [7]]
