In [1]:
import keras
import numpy as np

from keras.layers import Dense, Input
from keras.models import Model

x_train = np.array([[0,1],[2,3],[4,5]])
# y = x0 + x1
# y_train = np.sum(x_train, axis=1)
y_train = np.array([[x.sum()] for x in x_train])   # 2차원 array 형태
print('x_train:\n', x_train)
print('y_train:\n', y_train)

x_test = np.array([[6,7],[8,9]])
# y_test = np.sum(x_test, axis=1)
y_test = np.array([[x.sum()] for x in x_test])   # 2차원 array 형태
print('x_test:\n', x_test)
print('y_test:\n', y_test)

x = Input(shape=(2,))

h_layer1 = Dense(3)(x)
h_layer2 = Dense(2)(h_layer1)
y = Dense(1)(h_layer2)

model = Model(inputs=x, outputs=y)
model.summary()

model.compile('SGD', 'mse')
history = model.fit(x_train, y_train, batch_size=2, epochs=1000, verbose=0)

y_predict = model.predict(x_test)
print('y_predict'); print(y_predict)
print('y_test'); print(y_test)

Using TensorFlow backend.


x_train:
 [[0 1]
 [2 3]
 [4 5]]
y_train:
 [[1]
 [5]
 [9]]
x_test:
 [[6 7]
 [8 9]]
y_test:
 [[13]
 [17]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 2)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 3         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
y_predict
[[13.]
 [17.]]
y_test
[[13]
 [17]]
