In [1]:
import keras
import numpy as np

from keras.layers import Dense, Input
from keras.models import Model

x_train = np.array([[0],[1]])
y_train = x_train * 2 + 1
print('x_train:\n', x_train)
print('y_train:\n', y_train)

x_test = np.array([[2],[3]])
y_test = x_test * 2 + 1
print('x_test:\n', x_test)
print('y_test:\n', y_test)

x = Input(shape=(1,))

# d1 = Dense(2)
# h_layer = d1(x)
# d2 = Dense(1)
# y = d2(h_layer)

h_layer = Dense(2)(x)
y = Dense(1)(h_layer)

model = Model(inputs=x, outputs=y)
model.summary()

model.compile('SGD', 'mse')
history = model.fit(x_train, y_train, batch_size=2, epochs=1000, verbose=0)

y_predict = model.predict(x_test)
print('y_predict'); print(y_predict)
print('y_test'); print(y_test)

Using TensorFlow backend.


x_train:
 [[0]
 [1]]
y_train:
 [[1]
 [3]]
x_test:
 [[2]
 [3]]
y_test:
 [[5]
 [7]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 4         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 7
Trainable params: 7
Non-trainable params: 0
_________________________________________________________________
y_predict
[[4.99999 ]
 [6.999982]]
y_test
[[5]
 [7]]
