In [1]:
import keras
import numpy as np

from keras.layers import Dense, Input

x_train = np.array([[0],[1]])
y_train = x_train * 2 + 1
print('x_train:\n', x_train)
print('y_train:\n', y_train)

x_test = np.array([[2],[3]])
y_test = x_test * 2 + 1
print('x_test:\n', x_test)
print('y_test:\n', y_test)

Using TensorFlow backend.


x_train:
 [[0]
 [1]]
y_train:
 [[1]
 [3]]
x_test:
 [[2]
 [3]]
y_test:
 [[5]
 [7]]


In [2]:
x = Input(shape=(1,))
print(type(x))

<class 'tensorflow.python.framework.ops.Tensor'>


In [3]:
d = Dense(1)

In [4]:
y = d(x)    # callable class 이기 때문에 객체를 함수처럼 호출 가능
print(type(d))
print(type(y))

<class 'keras.layers.core.Dense'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [13]:
# [참고]callable class 만들기 (class에 __call__() 메서드 정의)
class Foo():
    def __init__(self):
        pass
    def __call__(self, x):
        print(x)

foo = Foo()
foo('haha')

haha


In [18]:
from keras.models import Model

model = Model(inputs=x, outputs=y)

In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile('SGD', 'mse')
history = model.fit(x_train, y_train, batch_size=2, epochs=1000, verbose=0)

y_predict = model.predict(x_test)
print('y_predict'); print(y_predict)
print('y_test'); print(y_test)

y_predict
[[4.999976 ]
 [6.9999585]]
y_test
[[5]
 [7]]
