### 2->3->2->1 네크워크에서 중간층의 출력 확인하기

#### 기본 네트워크(모델)

In [1]:
import keras
import numpy as np

from keras.layers import Dense, Input
from keras.models import Model

x_train = np.array([[0,1],[2,3],[4,5]])
# y = x0 + x1
# y_train = np.sum(x_train, axis=1)
y_train = np.array([[x.sum()] for x in x_train])   # 2차원 array 형태
print('x_train:\n', x_train)
print('y_train:\n', y_train)

x_test = np.array([[6,7],[8,9]])
# y_test = np.sum(x_test, axis=1)
y_test = np.array([[x.sum()] for x in x_test])   # 2차원 array 형태
print('x_test:\n', x_test)
print('y_test:\n', y_test)

x = Input(shape=(2,), name='x')

h_layer1 = Dense(3, name='hidden1')(x)
h_layer2 = Dense(2, name='hidden2')(h_layer1)
y = Dense(1, name='y')(h_layer2)

model = Model(inputs=x, outputs=y)
model.summary()

model.compile('SGD', 'mse')
history = model.fit(x_train, y_train, batch_size=3, epochs=1000, verbose=0)

y_predict = model.predict(x_test)
print('y_predict'); print(y_predict)
print('y_test'); print(y_test)

Using TensorFlow backend.


x_train:
 [[0 1]
 [2 3]
 [4 5]]
y_train:
 [[1]
 [5]
 [9]]
x_test:
 [[6 7]
 [8 9]]
y_test:
 [[13]
 [17]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               (None, 2)                 0         
_________________________________________________________________
hidden1 (Dense)              (None, 3)                 9         
_________________________________________________________________
hidden2 (Dense)              (None, 2)                 8         
_________________________________________________________________
y (Dense)                    (None, 1)                 3         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
y_predict
[[13.]
 [17.]]
y_test
[[13]
 [17]]


#### 중간층(hidden 1 layer) 확인하기

In [2]:
# outputs을 중간층의 layer로 지정하기
model_h = Model(inputs=x, outputs=h_layer1)
model_h.summary()

print('h1'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               (None, 2)                 0         
_________________________________________________________________
hidden1 (Dense)              (None, 3)                 9         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
h1
[[ 0.26832256  0.8867724   9.467402  ]
 [ 0.47792348  1.1920966  12.482029  ]]
y
[[13.]
 [17.]]


(None, None)

In [3]:
# 모델에 정의한 layer 이름
layer_h = model.get_layer('hidden1')
model_h = Model(inputs=model.input, outputs=layer_h.output)

print('h1'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

h1
[[ 0.26832256  0.8867724   9.467402  ]
 [ 0.47792348  1.1920966  12.482029  ]]
y
[[13.]
 [17.]]


(None, None)

In [4]:
# 모델의 index 사용
layer_h = model.get_layer(index=1)
model_h = Model(inputs=model.input, outputs=layer_h.output)

print('h1'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

h1
[[ 0.26832256  0.8867724   9.467402  ]
 [ 0.47792348  1.1920966  12.482029  ]]
y
[[13.]
 [17.]]


(None, None)

#### 중간층(hidden 2 layer) 확인하기

In [5]:
# outputs을 중간층의 layer로 지정하기
model_h = Model(inputs=x, outputs=h_layer2)
model_h.summary()

print('h2'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               (None, 2)                 0         
_________________________________________________________________
hidden1 (Dense)              (None, 3)                 9         
_________________________________________________________________
hidden2 (Dense)              (None, 2)                 8         
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________
h2
[[ 6.954959 10.443761]
 [ 9.093442 13.808617]]
y
[[13.]
 [17.]]


(None, None)

In [6]:
# 모델에 정의한 layer 이름
layer_h = model.get_layer('hidden2')
model_h = Model(inputs=model.input, outputs=layer_h.output)

print('h2'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

h2
[[ 6.954959 10.443761]
 [ 9.093442 13.808617]]
y
[[13.]
 [17.]]


(None, None)

In [7]:
# 모델의 index 사용
layer_h = model.get_layer(index=2)
model_h = Model(inputs=model.input, outputs=layer_h.output)

print('h2'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

h2
[[ 6.954959 10.443761]
 [ 9.093442 13.808617]]
y
[[13.]
 [17.]]


(None, None)