In [1]:
# 1->2->1 네크워브에서 중간층의 출력 확인하기
import keras
import numpy as np

from keras.layers import Dense, Input
from keras.models import Model

x_train = np.array([[0],[1]])
y_train = x_train * 2 + 1
print('x_train:\n', x_train)
print('y_train:\n', y_train)

x_test = np.array([[2],[3]])
y_test = x_test * 2 + 1
print('x_test:\n', x_test)
print('y_test:\n', y_test)

x = Input(shape=(1,), name='x')   # layer 이름 지정하기(option)
h_layer = Dense(2, name='hidden')(x)
y = Dense(1, name='y')(h_layer)

model = Model(inputs=x, outputs=y)
model.summary()

model.compile('SGD', 'mse')
history = model.fit(x_train, y_train, batch_size=2, epochs=1000, verbose=0)

y_predict = model.predict(x_test)
print('y_predict'); print(y_predict)
print('y_test'); print(y_test)

Using TensorFlow backend.


x_train:
 [[0]
 [1]]
y_train:
 [[1]
 [3]]
x_test:
 [[2]
 [3]]
y_test:
 [[5]
 [7]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               (None, 1)                 0         
_________________________________________________________________
hidden (Dense)               (None, 2)                 4         
_________________________________________________________________
y (Dense)                    (None, 1)                 3         
Total params: 7
Trainable params: 7
Non-trainable params: 0
_________________________________________________________________
y_predict
[[4.999996 ]
 [6.9999943]]
y_test
[[5]
 [7]]


In [2]:
# 중간층을 확인하기 위한 모델 만들기
model_h = Model(inputs=x, outputs=h_layer)    # outputs을 중간층의 layer로 지정
model_h.summary()

print('h'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               (None, 1)                 0         
_________________________________________________________________
hidden (Dense)               (None, 2)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
h
[[0.13101315 2.7197313 ]
 [0.34620306 3.944419  ]]
y
[[4.999996 ]
 [6.9999943]]


(None, None)

In [4]:
# Sequential model인 경우의 중간층 모델 확인하기
layer_h = model.get_layer('hidden')   # 모델에 정의한 layer 이름
model_h = Model(inputs=model.input, outputs=layer_h.output)

print('h'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

h
[[0.13101315 2.7197313 ]
 [0.34620306 3.944419  ]]
y
[[4.999996 ]
 [6.9999943]]


(None, None)

In [5]:
# 모델의 이름을 명시하지 않은 경우 중간층 모델 확인하기
layer_h = model.get_layer(index=1)   # 모델의 index 사용
model_h = Model(inputs=model.input, outputs=layer_h.output)

print('h'), print(model_h.predict(x_test))
print('y'), print(model.predict(x_test))

h
[[0.13101315 2.7197313 ]
 [0.34620306 3.944419  ]]
y
[[4.999996 ]
 [6.9999943]]


(None, None)