## Activation 함수를 Lambda layer로 구현하기

In [1]:
from keras import layers, models
import keras.backend as K
import numpy as np

x_test = np.array([[-1], [2]])
x = layers.Input((1,))

Using TensorFlow backend.


### sigmoid

In [3]:
y = layers.Activation('sigmoid')(x)
model = models.Model(x, y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred:\n', y_pred)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1)                 0         
_________________________________________________________________
activation_2 (Activation)    (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred:
 [[0.26894143]
 [0.880797  ]]


In [5]:
y = layers.Lambda(lambda x: 1 / (1 + K.exp(-x)))(x)
model = models.Model(x, y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred:\n', y_pred)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1)                 0         
_________________________________________________________________
lambda_2 (Lambda)            (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred:
 [[0.26894143]
 [0.880797  ]]


### tanh (hyperbolic tangent)

In [10]:
y = layers.Activation('tanh')(x)
model = models.Model(x, y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred:\n', y_pred)

# y = layers.Lambda(lambda x: (K.exp(2*x) - 1) / (K.exp(2*x) + 1))(x)
y = layers.Lambda(lambda x: (K.exp(x) - K.exp(-x)) / (K.exp(x) + K.exp(-x)))(x)
model = models.Model(x, y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred:\n', y_pred)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1)                 0         
_________________________________________________________________
activation_6 (Activation)    (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred:
 [[-0.7615942]
 [ 0.9640276]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1)                 0         
_________________________________________________________________
lambda_6 (Lambda)            (None, 1)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred:
 [[-0.7615942]
 [ 0.9640275]]


### ReLU

In [16]:
x_test = np.array([[-1, 1], [2, -3]])
x = layers.Input((2,))

y = layers.Activation('relu')(x)
model = models.Model(x, y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred:\n', y_pred)

#y = layers.Lambda(lambda x: K.switch(x>0, x, K.ones_like(x)*0))(x)
y = layers.Lambda(lambda x: K.max((K.ones_like(x)*0,x),axis=0))(x)
model = models.Model(x, y)
model.summary()
y_pred = model.predict(x_test)
print('y_pred:\n', y_pred)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 2)                 0         
_________________________________________________________________
activation_12 (Activation)   (None, 2)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred:
 [[0. 1.]
 [2. 0.]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 2)                 0         
_________________________________________________________________
lambda_12 (Lambda)           (None, 2)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
y_pred:
 [[0. 1.]
 [2. 0.]]
