여러개의 입력을 하나로 합치는 layer 들에 대해 공부해보겠습니다.

In [1]:
from keras import layers, models
import numpy as np

x_test_A = np.array([[0, 1], [4, 5]])
x_test_B = np.array([[2, 3], [6, 7]])

x_A = layers.Input(shape=(2,), name='x_A')
x_B = layers.Input(shape=(2,), name='x_B')

Using TensorFlow backend.


입력을 그대로 이어 붙이는 Concatenate

In [2]:
y = layers.Concatenate(name='concat')([x_A, x_B])
# y = layers.concatenate([x_A, x_B], name='concat')
model = models.Model(inputs=[x_A, x_B], outputs=y)
model.summary()
y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A'); print(x_test_A)
print('x_test_B'); print(x_test_B)
print('y_pred'); print(y_pred)

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
x_A (InputLayer)                (None, 2)            0                                            
__________________________________________________________________________________________________
x_B (InputLayer)                (None, 2)            0                                            
__________________________________________________________________________________________________
concat (Concatenate)            (None, 4)            0           x_A[0][0]                        
                                                                 x_B[0][0]                        
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
[[0 1]
 [4 5]]
x_test_B
[[2 3]
 [6 7]]
y

입력을 더해서 하나로 만드는 Add

In [3]:
y = layers.Add(name='add')([x_A, x_B])
# y = layers.add([x_A, x_B], name='add')
model = models.Model(inputs=[x_A, x_B], outputs=y)
model.summary()
y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A'); print(x_test_A)
print('x_test_B'); print(x_test_B)
print('y_pred'); print(y_pred)

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
x_A (InputLayer)                (None, 2)            0                                            
__________________________________________________________________________________________________
x_B (InputLayer)                (None, 2)            0                                            
__________________________________________________________________________________________________
add (Add)                       (None, 2)            0           x_A[0][0]                        
                                                                 x_B[0][0]                        
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
[[0 1]
 [4 5]]
x_test_B
[[2 3]
 [6 7]]
y

두 입력을 곱해서 하나로 만드는 Multiply

In [4]:
y = layers.Multiply(name='mul')([x_A, x_B])
# y = layers.multiply([x_A, x_B], name='mul')
model = models.Model(inputs=[x_A, x_B], outputs=y)
model.summary()
y_pred = model.predict([x_test_A, x_test_B])
print('x_test_A'); print(x_test_A)
print('x_test_B'); print(x_test_B)
print('y_pred'); print(y_pred)

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
x_A (InputLayer)                (None, 2)            0                                            
__________________________________________________________________________________________________
x_B (InputLayer)                (None, 2)            0                                            
__________________________________________________________________________________________________
mul (Multiply)                  (None, 2)            0           x_A[0][0]                        
                                                                 x_B[0][0]                        
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
x_test_A
[[0 1]
 [4 5]]
x_test_B
[[2 3]
 [6 7]]
y